#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          
          cat >> .config <<EOF
          CONFIG_TARGET_ipq807x=y

          CONFIG_TARGET_ipq807x_generic=y
          CONFIG_TARGET_ipq807x_generic_DEVICE_redmi_ax6=y

          CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSFORWARDER=y
          CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSPROXY=y

          #CONFIG_PACKAGE_TURBOACC_INCLUDE_OFFLOADING=y
          CONFIG_PACKAGE_kmod-ipt-offload=y
          CONFIG_PACKAGE_kmod-nf-flow=y
          #CONFIG_PACKAGE_TURBOACC_INCLUDE_SHORTCUT_FE=y
          #CONFIG_PACKAGE_kmod-fast-classifier=y
          #CONFIG_PACKAGE_kmod-shortcut-fe=y
          #CONFIG_PACKAGE_kmod-shortcut-fe-cm=y

          #??
          CONFIG_LUCI_LANG_en=y
          CONFIG_LUCI_LANG_zh_Hans=y

          CONFIG_PACKAGE_kmod-zram=y
          CONFIG_PACKAGE_zram-swap=y

          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_6rd=y
          CONFIG_PACKAGE_6to4=y


          # CONFIG_PACKAGE_kmod-usb-core is not set
          # CONFIG_PACKAGE_kmod-usb-dwc3 is not set
          # CONFIG_PACKAGE_kmod-usb3 is not set


          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set

          #CONFIG_PACKAGE_luci-app-adguardhome is not set

          CONFIG_PACKAGE_luci-app-easymesh=y

          #CONFIG_PACKAGE_luci-app-frpc is not set
          #CONFIG_PACKAGE_luci-app-frps is not set

          CONFIG_PACKAGE_luci-app-guest-wifi=y


          #CONFIG_PACKAGE_luci-app-aliyundrive-webdav is not set

          #CONFIG_PACKAGE_luci-app-jd-dailybonus is not set

          #CONFIG_PACKAGE_luci-app-mwan3=y
          #CONFIG_PACKAGE_luci-app-mwan3helper=y
          #CONFIG_PACKAGE_luci-app-dawn=y
          #CONFIG_PACKAGE_luci-app-n2n_v2=y

          CONFIG_PACKAGE_luci-app-netdata=y

          CONFIG_PACKAGE_luci-app-ntpc=y
          CONFIG_PACKAGE_luci-app-dnsfilter=y
          #CONFIG_PACKAGE_luci-app-nps=y

          #CONFIG_PACKAGE_luci-app-oaf=y

          #CONFIG_PACKAGE_luci-app-openclash=y

          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set

          CONFIG_PACKAGE_luci-app-pppoe-relay=y

          CONFIG_PACKAGE_luci-app-pptp-server=y

          CONFIG_PACKAGE_luci-app-pushbot=y

          CONFIG_PACKAGE_luci-app-qos=y

          #CONFIG_PACKAGE_luci-app-smartdns=y

          CONFIG_PACKAGE_luci-app-sqm=y

          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Client=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Server=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_Obfs=y

          CONFIG_PACKAGE_luci-app-syncdial=y

          CONFIG_PACKAGE_luci-app-ttyd=y

          CONFIG_PACKAGE_luci-app-udpxy=y

          CONFIG_PACKAGE_luci-app-uhttpd=y

          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go is not set

          #CONFIG_PACKAGE_luci-app-uugamebooster=y

          #CONFIG_PACKAGE_luci-app-vlmcsd=y

          # CONFIG_PACKAGE_luci-app-vsftpd is not set

          #CONFIG_PACKAGE_luci-app-wifischedule=y

          #CONFIG_PACKAGE_luci-app-wireguard=y

          #CONFIG_PACKAGE_luci-proto-wireguard=y
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set

          CONFIG_PACKAGE_luci-theme-infinityfreedom=y
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
